[package]
name = "mapeditr"
version = "1.1.0"
authors = ["random-geek (github.com/random-geek)"]
edition = "2018"

[dependencies]
	anyhow = "1"
	byteorder = "1"
	clap = "2"
	flate2 = "1"
	memmem = "0.1"
	sqlite = "0.26"
	thiserror = "1"
	zstd = "0.11"
