[package]
name = "mapeditr"
version = "0.1.0"
authors = ["random-geek <35757396+random-geek@users.noreply.github.com>"]
edition = "2018"

[dependencies]
	sqlite = "0.25"
	flate2 = "1"
	clap = "2"
	byteorder = "1"
	memmem = "0.1"
	anyhow = "1"
	thiserror = "1"
