name: Publish binaries

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish binaries for Windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Build
      run: |
        cargo build --release --locked
        tar.exe -c -a -f mapeditr-windows.zip target/release/mapeditr.exe LICENSE.txt README.md Manual.md

    - name: Upload artifacts to release
      uses: softprops/action-gh-release@v1
      with:
        files: mapeditr-windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
